import "./globals.css";

export const metadata = {
  title: "FakeAstro",
  description:
    "Generated by a human: Trevor Brown. Can you tell fact from scifiction??????",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-800 text-slate-200 ">{children}</body>
    </html>
  );
}
